version: '3'
services:
  minecraft:
    build:
      context: .
    container_name: minecraft-server
    volumes:
      - minecraft-data:/etc/minecraft
    ports:
      - "25565:25565"
    environment:
      - _JAVA_OPTIONS=-Xms256M -Xmx6000M
    restart: unless-stopped

volumes:
  minecraft-data:
